### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by Pollito001** [RupertAvery/PSXPackager#14]
It is posible to add linux support?

**Comment by bryanperris** [comment]
Compile (`dotnet build`) my fork using the dotnet 6 sdk for linux: https://github.com/bryanperris/PSXPackager
I upgraded the entire project to dotnet 6; The only feature not supported on non-windows platforms is unpacking archived/compressed files due to SevenZipSharp (Squid-Box) supporting only Windows.  So you must only input raw uncompressed CD files (eg: CUE/BIN)
I removed the GUI project since WPF is not cross-platform, I would recommend using Avalonia to anyone interested in making a C# cross-platform GUI app.

**Comment by RupertAvery** [comment]
Latest release has linux build, without compressed file support.

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.6.0

But for a UI I would have to rewrite the GUI using Avalonia. Not familiar with it yet and it will take time to port it.
