### ISSUE TITLE
PSXPackager GUI Work in progress

### ISSUE THREAD

**Issue by RupertAvery** [RupertAvery/PSXPackager#6]
Due to recent interest in the project, I've decided to start work on a GUI, with focus around batch processing.

![image](https://user-images.githubusercontent.com/1910659/101668269-46f10d80-3a8b-11eb-9ad1-27d61bfd7759.png)

**Comment by BadBrent** [comment]
Well done!  There are hundreds of us looking forward to this.  The community of us that only use RetroArch to launch PBPs will be excited because we don't care about the artwork most PBP conversion tools tries to get you to add, and if multi-game PBPs can be implemented you'll have a wonderful tool that will allow us to mass convert our PS1 images easily.  I've been spreading work of your progress to the Retro Game Handhelds community on Discord and many people are getting excited about this development of this project and are thrilled.

**Comment by bezza191** [comment]
Just to say - keep up the great work @RupertAvery looking forward to this GUI

**Comment by Quest79** [comment]
Thanks for this. Any way we can try this out for testing?

**Comment by blueturtleshells** [comment]
Donde esta el version de la UI?

**Comment by kenneth-leblanc** [comment]
Any update on this? I would be interesting in testing as well.

**Comment by RupertAvery** [comment]
Hi, if your're interested, there is a beta version of PSXPackagerGUI

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.5.0
